# Generated by Django 5.1.5 on 2025-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('accrued_salary', models.FloatField(verbose_name='Начислено за отработанное время, руб.')),
                ('bonus', models.FloatField(verbose_name='Бонус, руб.')),
                ('salary', models.FloatField(verbose_name='Зарплата, руб.')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'историческия зарплата',
                'verbose_name_plural': 'Зарплаты Исторические',
            },
        ),
    ]
