# Generated by Django 5.1.5 on 2025-04-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0002_salaryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код сотрудника'),
        ),
    ]
