# Generated by Django 5.1.5 on 2025-04-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0003_alter_salaryhistory_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryhistory',
            options={'ordering': ['-period'], 'verbose_name': 'историческия зарплата', 'verbose_name_plural': 'Зарплаты Исторические'},
        ),
    ]
