# Generated by Django 5.1.5 on 2025-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0005_timesheethistory_alter_salaryhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheethistory',
            options={'ordering': ['-period', 'employee', '-date'], 'verbose_name': 'исторический табель', 'verbose_name_plural': 'История-Табель'},
        ),
        migrations.AddField(
            model_name='timesheethistory',
            name='date',
            field=models.DateField(default='2025-01-01', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='timesheethistory',
            name='timesheet_data',
            field=models.CharField(max_length=20, verbose_name='Табель'),
        ),
    ]
