# Generated by Django 5.1.5 on 2025-04-03 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0006_alter_timesheethistory_options_timesheethistory_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField(verbose_name='Плановый день начала отпуска')),
                ('planned_end_date', models.DateField(verbose_name='Плановый день окончания отпуска')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Фактический день начала отпуска')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактический день окончания отпуска')),
                ('planned_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Количество дней отпуска по плану')),
                ('remaining_days', models.IntegerField(default=0, verbose_name='Количество дней отпуска осталось')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_data.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
                'ordering': ['planned_start_date'],
            },
        ),
    ]
