# Generated by Django 5.1.5 on 2025-04-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0008_alter_vacation_planned_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='code',
            field=models.IntegerField(default=13, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
