# Generated by Django 5.1.5 on 2025-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('bonus', models.FloatField(default=0, verbose_name='Бонус, руб.')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('accrued_salary', models.FloatField(verbose_name='Начислено за отработанное время, руб.')),
                ('bonus', models.FloatField(verbose_name='Бонус, руб.')),
                ('salary', models.FloatField(verbose_name='Зарплата, руб.')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Зарплата',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('timesheet_data', models.CharField(max_length=20, verbose_name='Табель сотрудника')),
            ],
            options={
                'verbose_name': 'табель сотрудника',
                'verbose_name_plural': 'Табель сотрудников',
            },
        ),
        migrations.CreateModel(
            name='TimeSheetAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('timesheet_data', models.CharField(max_length=20, verbose_name='Инфо')),
            ],
            options={
                'verbose_name': 'табель сотрудника',
                'verbose_name_plural': 'Табель отсутствия сотрудников',
            },
        ),
        migrations.CreateModel(
            name='UploadTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('timesheet_data', models.CharField(max_length=20, verbose_name='Час/Инфо')),
            ],
            options={
                'verbose_name': 'табель сотрудника',
                'verbose_name_plural': 'Табель Загрузка',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код сотрудника')),
                ('employee', models.CharField(max_length=150, verbose_name='Сотрудник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отработано часов')),
            ],
            options={
                'verbose_name': 'сотрудника',
                'verbose_name_plural': 'Табель рабочего времени',
            },
        ),
    ]
