# Generated by Django 5.1.5 on 2025-04-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'verbose_name': 'табель сотрудника', 'verbose_name_plural': 'Табель общий сотрудников'},
        ),
    ]
