# Generated by Django 5.1.5 on 2025-04-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_cost', '0002_alter_timesheet_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
